Bot:
  first_layer:
    type: 'conv2d'
    filters: 64
    kernel_size:
      - 4
      - 4
    strides:
      - 1
      - 1
    padding: 'same'
    activation:
      type: 'leakyrelu'
      alpha: 0.3
    kernel_regularizer:
      type: 'l1_l2'
      value:
        - 0.0005
        - 0.0005
    kernel_initializer:
      type: 'he_uniform'
      value: 123456
    flatten:
      value: False
    dropout:
      rate: 0.25
  second_layer:
    type: 'conv2d'
    filters: 64
    kernel_size:
      - 4
      - 4
    strides:
      - 1
      - 1
    padding: 'same'
    activation:
      type: 'leakyrelu'
      alpha: 0.3
    kernel_regularizer:
      type: 'l1_l2'
      value:
        - 0.0005
        - 0.0005
    kernel_initializer:
      type: 'he_uniform'
      value: 123456
    flatten:
      value: True
    dropout:
      rate: 0.25
  third_layer:
    type: 'dense'
    units: 100
    activation:
      type: 'leakyrelu'
      alpha: 0.3
    kernel_regularizer:
      type: 'l1_l2'
      value:
      - 0.0005
      - 0.0005
    kernel_initializer:
      type: 'he_uniform'
      value: 123456
    flatten:
      value: True
